<?php

namespace Admin\AccessControlBundle\Repository;

/**
 * DataPrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataPrivilegeRepository extends \Doctrine\ORM\EntityRepository
{
}
