<?php

namespace Admin\AccessControlBundle\Repository;

/**
 * PagePrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagePrivilegeRepository extends \Doctrine\ORM\EntityRepository
{
}
