<?php

namespace Admin\AccessControlBundle\Repository;

/**
 * UserTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTreeRepository extends \Doctrine\ORM\EntityRepository
{
}
