<?php

namespace Admin\ConsoleBundle\Repository;

/**
 * SiteConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
