admin_client:
    resource: "@AdminClientBundle/Controller/"
    type:     annotation
    prefix:   /

admin_console:
    resource: "@AdminConsoleBundle/Controller/"
    type:     annotation
    prefix:   /

admin_access_control:
    resource: "@AdminAccessControlBundle/Controller/"
    type:     annotation
    prefix:   /

admin_user:
    resource: "@AdminUserBundle/Controller/"
    type:     annotation
    prefix:   /
admin_verfiy:
    resource: "@AdminVerifyBundle/Controller/"
    type: annotation
    prefix:   /