# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_decision_manager:
        strategy: unanimous
    encoders:
        Admin\UserBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        admin_db_provider:
            entity:
                class: Admin\UserBundle\Entity\User
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_security:
            # anonymous: ~
            pattern: ^/(admin|login_check|logout)
            provider: admin_db_provider
            form_login:
                target_path_parameter: redirect_url
                #csrf_parameter: csrf_token
                # intention: bjh
                #csrf_provider: form.csrf_provider
                check_path: admin_login_check
                login_path: admin_login
                # authenticator: admin_dwz_backend_authcode_authenticator
                # success_handler: admin_dwz_backend.loginSuccess
            logout:
                path: admin_console_logout
                target: /login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path:^/admin, roles: IS_AUTHENTICATED_FULLY }
