services:
    admin_accesscontrol.accesscontrol_voter:
        class: Admin\AccessControlBundle\Security\AccessControlVoter
        arguments:
          ["@router","@doctrine"]
        tags:
            - { name: security.voter }
        public: false
    admin_accesscontrol.dataaccesscontrol_voter:
        class: Admin\AccessControlBundle\Security\DataAccessControlVoter
        arguments:
          ["@router","@doctrine"]
        tags:
            - { name: security.voter }
        public: false
