services:
    admin_user.twig_filter_extesion:
        class: Admin\UserBundle\Extension\TwigFilterExtension
        public: true 
        tags:
            - { name: twig.extension }
    admin_user.form.type.user:
        class: Admin\UserBundle\Form\TaskType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }
