services:
    admin_console.twig_filter_extesion:
        class: Admin\ConsoleBundle\Extension\TwigFilterExtension
        public: true 
        tags:
            - { name: twig.extension }
    admin_console.pager:
        class: Admin\ConsoleBundle\Extension\PagerExtension
        public: true 
        arguments:
          - {pageSize: 5, firstText: '&lt;&lt;', lastText: '&rt;&rt;', preText: '&lt;', nextText: '&rt;', className: ''}
