services:
    admin_console.twig_filter_extesion:
        class: Admin\ConsoleBundle\Extension\TwigFilterExtension
        public: true 
        tags:
            - { name: twig.extension }
    admin_console.pager:
        class: Admin\ConsoleBundle\Extension\PagerExtension
        public: true 
        arguments:
          - {pageSize: 20, firstText: '&lt;&lt;', lastText: '&gt;&gt;', preText: '&lt;', nextText: '&gt;', className: ''}
    admin_console.form.type.siteconfig:
        class: Admin\ConsoleBundle\Form\SiteConfigType
        arguments: ["@router"]
        tags:
            - { name: form.type }
    admin_dwz_backend.exception_listener:
        class: Admin\ConsoleBundle\Extension\ConsoleExceptionListener
        arguments: [@translator]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }