<?php

namespace Admin\ClientBundle\Repository;

/**
 * ClientAccessRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAccessRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
